# Generated by Django 4.2.8 on 2024-01-02 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronSchedulers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='触发器名称')),
                ('year', models.CharField(blank=True, max_length=50, null=True, verbose_name='年份(2020)')),
                ('month', models.CharField(blank=True, max_length=50, null=True, verbose_name='月份(1-12)')),
                ('day', models.CharField(blank=True, max_length=50, null=True, verbose_name='日期(1-31)')),
                ('week', models.CharField(blank=True, max_length=50, null=True, verbose_name='周数(1-53)')),
                ('day_of_week', models.CharField(blank=True, max_length=50, null=True, verbose_name='工作日(0-6)；0为周一')),
                ('hour', models.CharField(blank=True, max_length=50, null=True, verbose_name='小时(0-23)')),
                ('minute', models.CharField(blank=True, max_length=50, null=True, verbose_name='分钟(0-59)')),
                ('second', models.CharField(blank=True, max_length=50, null=True, verbose_name='秒数(0-59)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_author', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '5、特定时间周期性地触发器',
                'verbose_name_plural': '5、特定时间周期性地触发器',
            },
        ),
        migrations.CreateModel(
            name='DateSchedulers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='触发器名称')),
                ('datetime', models.DateTimeField(verbose_name='开始时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_author', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '3、特定的时间点触发器',
                'verbose_name_plural': '3、特定的时间点触发器',
            },
        ),
        migrations.CreateModel(
            name='IntervalSchedulers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='触发器名称')),
                ('weeks', models.IntegerField(blank=True, default=0, null=True, verbose_name='间隔周数')),
                ('days', models.IntegerField(blank=True, default=0, null=True, verbose_name='间隔天数')),
                ('hours', models.IntegerField(blank=True, default=0, null=True, verbose_name='间隔小时数')),
                ('minutes', models.IntegerField(blank=True, default=0, null=True, verbose_name='间隔分钟数')),
                ('seconds', models.IntegerField(blank=True, default=0, null=True, verbose_name='间隔秒数')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始日期')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_author', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '4、固定时间间隔触发器',
                'verbose_name_plural': '4、固定时间间隔触发器',
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('level', models.CharField(blank=True, default='1', max_length=10, verbose_name='等级')),
                ('job_id', models.IntegerField(verbose_name='任务ID')),
                ('type', models.CharField(choices=[('0', '脚本任务'), ('1', 'API调用任务'), ('2', '通用任务')], max_length=10, verbose_name='类型')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
            },
        ),
        migrations.CreateModel(
            name='ScriptJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='任务名称')),
                ('trigger', models.CharField(choices=[('date', '特定的时间点触发器'), ('interval', '固定时间间隔触发器'), ('cron', '特定时间周期性地触发器')], max_length=10, verbose_name='触发器类型')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('next_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('job_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='任务id')),
                ('enable', models.CharField(choices=[('0', '启用'), ('1', '停用'), ('2', '失效')], default=1, max_length=5, verbose_name='当前状态')),
                ('ReceiversEmail', models.CharField(max_length=200, verbose_name='接受方邮件地址(多个用 | 分开)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('script_type', models.CharField(choices=[('1', 'python')], default='1', max_length=10, verbose_name='语言类型')),
                ('script_content', models.TextField(verbose_name='脚本内容')),
                ('script_timeout', models.IntegerField(default=300, verbose_name='执行超时时间(s)')),
                ('type', models.CharField(choices=[('0', '脚本任务'), ('1', 'API调用任务'), ('2', '通用任务')], default='0', max_length=10, verbose_name='类型')),
                ('CronSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.cronschedulers', verbose_name='特定时间周期性地触发器')),
                ('DateSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.dateschedulers', verbose_name='特定的时间点触发器')),
                ('IntervalSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.intervalschedulers', verbose_name='固定时间间隔触发器')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_job_author', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '脚本执行任务',
                'verbose_name_plural': '脚本执行任务',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EmailType', models.CharField(choices=[('1', 'Exchange邮箱'), ('2', '其他邮箱')], default=2, max_length=10, verbose_name='邮箱类型')),
                ('EmailServer', models.CharField(max_length=50, verbose_name='邮箱服务器地址')),
                ('SendEmailAdd', models.EmailField(max_length=254, verbose_name='发送方邮件地址')),
                ('SendEmailUser', models.CharField(max_length=50, verbose_name='发送方邮件账户')),
                ('SendEmailPsd', models.CharField(max_length=100, verbose_name='发送放邮件密码')),
                ('ReceiversEmail', models.CharField(max_length=200, verbose_name='接受方邮件地址(仅用于邮件测试)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_author', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '6、邮件告警配置',
                'verbose_name_plural': '6、邮件告警配置',
            },
        ),
        migrations.CreateModel(
            name='CommonJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='任务名称')),
                ('trigger', models.CharField(choices=[('date', '特定的时间点触发器'), ('interval', '固定时间间隔触发器'), ('cron', '特定时间周期性地触发器')], max_length=10, verbose_name='触发器类型')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('next_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('job_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='任务id')),
                ('enable', models.CharField(choices=[('0', '启用'), ('1', '停用'), ('2', '失效')], default=1, max_length=5, verbose_name='当前状态')),
                ('ReceiversEmail', models.CharField(max_length=200, verbose_name='接受方邮件地址(多个用 | 分开)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('path', models.CharField(default='path1/path2/path3.func1', max_length=1024, verbose_name='模块路径')),
                ('params', models.TextField(blank=True, default='', verbose_name='参数, json格式')),
                ('type', models.CharField(choices=[('0', '脚本任务'), ('1', 'API调用任务'), ('2', '通用任务')], default='2', max_length=10, verbose_name='类型')),
                ('CronSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.cronschedulers', verbose_name='特定时间周期性地触发器')),
                ('DateSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.dateschedulers', verbose_name='特定的时间点触发器')),
                ('IntervalSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.intervalschedulers', verbose_name='固定时间间隔触发器')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_job_author', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通用执行任务',
                'verbose_name_plural': '通用执行任务',
            },
        ),
        migrations.CreateModel(
            name='ApiJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='任务名称')),
                ('trigger', models.CharField(choices=[('date', '特定的时间点触发器'), ('interval', '固定时间间隔触发器'), ('cron', '特定时间周期性地触发器')], max_length=10, verbose_name='触发器类型')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('next_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('job_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='任务id')),
                ('enable', models.CharField(choices=[('0', '启用'), ('1', '停用'), ('2', '失效')], default=1, max_length=5, verbose_name='当前状态')),
                ('ReceiversEmail', models.CharField(max_length=200, verbose_name='接受方邮件地址(多个用 | 分开)')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('url', models.CharField(max_length=255, verbose_name='网址')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('PUT', 'PUT'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='方法')),
                ('params', models.TextField(blank=True, default='', verbose_name='命令行参数, json格式')),
                ('json_data', models.TextField(blank=True, default='', verbose_name='post application/json 请求参数')),
                ('form_data', models.TextField(blank=True, default='', verbose_name='post form 请求参数')),
                ('headers', models.TextField(blank=True, default='', verbose_name='请求头 json格式')),
                ('verify', models.BooleanField(default=False, verbose_name='忽略 https 校验')),
                ('type', models.CharField(choices=[('0', '脚本任务'), ('1', 'API调用任务'), ('2', '通用任务')], default='1', max_length=10, verbose_name='类型')),
                ('CronSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.cronschedulers', verbose_name='特定时间周期性地触发器')),
                ('DateSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.dateschedulers', verbose_name='特定的时间点触发器')),
                ('IntervalSchedulers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulers.intervalschedulers', verbose_name='固定时间间隔触发器')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_job_author', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'HTTP API执行任务',
                'verbose_name_plural': 'HTTP API执行任务',
            },
        ),
    ]
