# Generated by Django 3.1.4 on 2021-03-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='EmailType',
            field=models.CharField(choices=[('1', 'Exchange邮箱'), ('2', '其他邮箱')], default=2, max_length=10, verbose_name='邮箱类型'),
        ),
        migrations.AddField(
            model_name='schedulersjob',
            name='password_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='schedulersjob',
            name='username_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='登录用户名'),
        ),
        migrations.AddField(
            model_name='schedulersjob2',
            name='login_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='登录地址'),
        ),
        migrations.AddField(
            model_name='schedulersjob2',
            name='password_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='schedulersjob2',
            name='username_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='登录用户名'),
        ),
        migrations.AlterField(
            model_name='schedulersjob',
            name='nextbutton',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='下一页按钮的XPath'),
        ),
        migrations.AlterField(
            model_name='schedulersjob2',
            name='nextbutton',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='下一页按钮的XPath'),
        ),
    ]
