# Generated by Django 4.2.8 on 2024-01-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='level',
            field=models.CharField(blank=True, default='0', max_length=10, verbose_name='等级'),
        ),
    ]
