# Generated by Django 3.1.4 on 2021-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0002_auto_20210316_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersjob',
            name='islazyload',
            field=models.BooleanField(default=False, verbose_name='是否为懒加载网站'),
        ),
        migrations.AddField(
            model_name='schedulersjob',
            name='mask_keys',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='存放招标信息的关键字(多个用 | 分开)'),
        ),
        migrations.AddField(
            model_name='schedulersjob',
            name='url_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='存放详细页网址的关键字'),
        ),
    ]
